Repository TrubitTech/trubit-tech, pull requests merged in 2022-06, with the labels that each got.

#18 Feat/foundation consumer backend
  .changeset/nine-parrots-juggle.md
  applications/consumer-backend/. prettierrc
  applications/consumer-backend/.gitignore
  applications/consumer-backend/README.md
  applications/consumer-backend/index.ts
  applications/consumer-backend/middlewares/genericErrorHandler.ts
  applications/consumer-backend/middlewares/index.ts
  applications/consumer-backend/middlewares/notFoundErrorHandler.ts
  applications/consumer-backend/modules/index.ts
  applications/consumer-backend/modules/user/index.ts
  applications/consumer-backend/modules/user/userController.ts
  applications/consumer-backend/modules/user/userModel.ts
  applications/consumer-backend/modules/user/userRoutes.ts
  applications/consumer-backend/nodemon.json
  applications/consumer-backend/package.json
  applications/consumer-backend/server.ts
  applications/consumer-backend/tsconfig.json
  applications/consumer-backend/utils/environmentVariables.ts
  applications/consumer-backend/utils/index.ts
  applications/consumer-backend/utils/logger/index.ts
  applications/consumer-backend/utils/logger/morgan.ts
  applications/consumer-backend/utils/logger/winston.ts
  applications/consumer-backend/utils/responseHandler.ts
  yarn.lock
Labels: infrastructure

#20 [CU-27dbyy3] create gaia package foundations
  package.json
  packages/gaia/README.md
  packages/gaia/__tests__/operations.test.ts
  packages/gaia/__tests__/setup.ts
  packages/gaia/jest.config.js
  packages/gaia/package.json
  packages/gaia/src/constants.ts
  packages/gaia/src/index.ts
  packages/gaia/src/modules/delete.ts
  packages/gaia/src/modules/get.ts
  packages/gaia/src/modules/index.ts
  packages/gaia/src/modules/list.ts
  packages/gaia/src/modules/put.ts
  packages/gaia/src/types.ts
  packages/gaia/tsconfig.json
  packages/ui/package.json
  packages/ui/src/theme/defaults/utils.ts
  tsconfig.base.json
  yarn.lock
Labels: @trubittech/ui

#21 feat: add test step(s) to PR workflow
  .github/workflows/analyze_pull_request.yml
  .github/workflows/publish_new_releases.yml
  packages/gaia/package.json
  packages/gaia/test-results.json
Labels: workflows
